version: '3.8'

services:
  # Main Wails application
  device-agent:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: device-agent
    ports:
      - "8080:8080"
    environment:
      - ENV=production
      - PORT=8080
    volumes:
      # Mount config directory if needed
      - ./config:/root/config:ro
      # Mount logs directory
      - ./logs:/root/logs
    restart: unless-stopped
    networks:
      - device-agent-network

  # Optional: Add a reverse proxy (nginx)
  nginx:
    image: nginx:alpine
    container_name: device-agent-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - device-agent
    restart: unless-stopped
    networks:
      - device-agent-network

  # Optional: Add a database if needed (PostgreSQL example)
  postgres:
    image: postgres:15-alpine
    container_name: device-agent-db
    environment:
      POSTGRES_DB: device_agent
      POSTGRES_USER: device_agent
      POSTGRES_PASSWORD: your_secure_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - device-agent-network

  # Optional: Add Redis for caching/sessions
  redis:
    image: redis:7-alpine
    container_name: device-agent-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - device-agent-network
    command: redis-server --appendonly yes

volumes:
  postgres_data:
  redis_data:

networks:
  device-agent-network:
    driver: bridge